name: flight_time
description: "Compute the flight time of a jump using the video camera"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  camerawesome: ^2.1.0
  video_player: ^2.9.2
  cupertino_icons: ^1.0.8
  sembast: ^3.7.5
  path: ^1.9.0
  path_provider: ^2.1.4
  intl: ^0.19.0
  flutter_video_info: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  path_provider_linux: ^2.2.1

flutter:
  uses-material-design: true
